import '../models/question_model.dart';

final List<QuestionModel> curatedCcseQuestionsPhase2 = [
  _question(
    id: 'ccse-251',
    task: 'Gobierno, legislación y participación ciudadana',
    topic: 'Referéndum constitucional',
    prompt: '¿Cómo se aprobó finalmente la Constitución española de 1978?',
    optionA: 'Por referéndum de la ciudadanía',
    optionB: 'Por decisión exclusiva del Gobierno',
    optionC: 'Por votación municipal',
    optionD: 'Por decreto del Tribunal Supremo',
    correctOptionId: 'a',
    explanation: 'La Constitución fue ratificada por la ciudadanía mediante referéndum.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-252',
    task: 'Gobierno, legislación y participación ciudadana',
    topic: 'Consejo de Ministros',
    prompt: '¿Quiénes forman el Consejo de Ministros?',
    optionA: 'El presidente del Gobierno y los ministros',
    optionB: 'Solo los diputados del Congreso',
    optionC: 'Los alcaldes de las capitales de provincia',
    optionD: 'Los jueces del Tribunal Constitucional',
    correctOptionId: 'a',
    explanation: 'El Consejo de Ministros está integrado por el presidente y los ministros.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-253',
    task: 'Gobierno, legislación y participación ciudadana',
    topic: 'Soberanía nacional',
    prompt: 'Según la Constitución, ¿de quién emanan los poderes del Estado?',
    optionA: 'Del pueblo español',
    optionB: 'Del Senado exclusivamente',
    optionC: 'Del rey',
    optionD: 'De los partidos políticos',
    correctOptionId: 'a',
    explanation: 'La soberanía nacional reside en el pueblo español.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-254',
    task: 'Gobierno, legislación y participación ciudadana',
    topic: 'Senado',
    prompt: '¿Qué cámara representa de manera especial al territorio en España?',
    optionA: 'El Senado',
    optionB: 'El Congreso de los Diputados',
    optionC: 'El Tribunal Supremo',
    optionD: 'El Consejo de Estado',
    correctOptionId: 'a',
    explanation: 'El Senado es la cámara de representación territorial.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-255',
    task: 'Gobierno, legislación y participación ciudadana',
    topic: 'Defensor del Pueblo',
    prompt: '¿Qué institución defiende los derechos fundamentales frente a la actuación de la Administración?',
    optionA: 'El Defensor del Pueblo',
    optionB: 'La Agencia Tributaria',
    optionC: 'El Banco de España',
    optionD: 'La Dirección General de Tráfico',
    correctOptionId: 'a',
    explanation: 'El Defensor del Pueblo supervisa la actividad administrativa y protege derechos.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-256',
    task: 'Gobierno, legislación y participación ciudadana',
    topic: 'Boletín Oficial',
    prompt: '¿Dónde se publican oficialmente muchas leyes y normas estatales?',
    optionA: 'En el Boletín Oficial del Estado',
    optionB: 'En la biblioteca nacional',
    optionC: 'En el registro civil',
    optionD: 'En el padrón municipal',
    correctOptionId: 'a',
    explanation: 'El BOE es el diario oficial en el que se publican leyes y disposiciones estatales.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-257',
    task: 'Gobierno, legislación y participación ciudadana',
    topic: 'Presidente del Gobierno',
    prompt: '¿Quién propone normalmente a los ministros del Gobierno?',
    optionA: 'El presidente del Gobierno',
    optionB: 'El Senado',
    optionC: 'El alcalde de Madrid',
    optionD: 'El Consejo General del Poder Judicial',
    correctOptionId: 'a',
    explanation: 'El presidente del Gobierno propone la composición del Ejecutivo.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-258',
    task: 'Gobierno, legislación y participación ciudadana',
    topic: 'Participación ciudadana',
    prompt: '¿Qué acción refleja una forma habitual de participación ciudadana en democracia?',
    optionA: 'Presentar una queja o sugerencia ante una administración',
    optionB: 'Sustituir a los tribunales',
    optionC: 'Anular leyes por cuenta propia',
    optionD: 'Impedir las elecciones',
    correctOptionId: 'a',
    explanation: 'Las personas pueden participar también mediante quejas, propuestas y otros canales legales.',
    difficulty: 'fácil',
  ),
  _question(
    id: 'ccse-259',
    task: 'Gobierno, legislación y participación ciudadana',
    topic: 'Moción de censura',
    prompt: '¿Qué instrumento parlamentario permite intentar sustituir al presidente del Gobierno?',
    optionA: 'La moción de censura',
    optionB: 'El recurso de amparo',
    optionC: 'La iniciativa legislativa popular',
    optionD: 'El indulto',
    correctOptionId: 'a',
    explanation: 'La moción de censura es un mecanismo parlamentario previsto en la Constitución.',
    difficulty: 'alta',
  ),
  _question(
    id: 'ccse-260',
    task: 'Gobierno, legislación y participación ciudadana',
    topic: 'Administración local',
    prompt: 'Además del ayuntamiento, ¿qué otra entidad provincial puede prestar servicios a municipios pequeños?',
    optionA: 'La diputación provincial',
    optionB: 'La Unión Europea',
    optionC: 'El Congreso de los Diputados',
    optionD: 'El Tribunal de Cuentas',
    correctOptionId: 'a',
    explanation: 'Las diputaciones provinciales apoyan a muchos municipios en la prestación de servicios.',
    difficulty: 'alta',
  ),
  _question(
    id: 'ccse-261',
    task: 'Derechos y deberes fundamentales',
    topic: 'Tutela judicial',
    prompt: 'Si una persona considera vulnerados sus derechos, ¿a qué puede acudir para defenderse legalmente?',
    optionA: 'A los tribunales de justicia',
    optionB: 'A una oficina de turismo',
    optionC: 'A una farmacia',
    optionD: 'A un museo',
    correctOptionId: 'a',
    explanation: 'La tutela judicial efectiva permite acudir a los tribunales para defender derechos.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-262',
    task: 'Derechos y deberes fundamentales',
    topic: 'Libertad de expresión',
    prompt: '¿Qué derecho protege la posibilidad de difundir libremente opiniones e información?',
    optionA: 'La libertad de expresión',
    optionB: 'La libertad de circulación',
    optionC: 'La libertad de empresa',
    optionD: 'La libertad de residencia turística',
    correctOptionId: 'a',
    explanation: 'La libertad de expresión ampara la difusión de opiniones e información dentro de la ley.',
    difficulty: 'fácil',
  ),
  _question(
    id: 'ccse-263',
    task: 'Derechos y deberes fundamentales',
    topic: 'Protección de datos',
    prompt: '¿Qué idea está relacionada con la protección de datos personales?',
    optionA: 'Que la información privada debe tratarse con garantías legales',
    optionB: 'Que cualquier dato puede publicarse sin permiso',
    optionC: 'Que solo importan los datos económicos',
    optionD: 'Que internet no tiene reglas',
    correctOptionId: 'a',
    explanation: 'Los datos personales deben protegerse y tratarse conforme a la normativa.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-264',
    task: 'Derechos y deberes fundamentales',
    topic: 'Huelga',
    prompt: '¿Qué derecho permite a los trabajadores defender sus intereses laborales mediante la suspensión colectiva del trabajo?',
    optionA: 'El derecho de huelga',
    optionB: 'El derecho de sufragio',
    optionC: 'El derecho de propiedad',
    optionD: 'El derecho de empadronamiento',
    correctOptionId: 'a',
    explanation: 'La huelga es un derecho reconocido para la defensa de intereses laborales.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-265',
    task: 'Derechos y deberes fundamentales',
    topic: 'Asistencia sanitaria',
    prompt: '¿Qué nivel de gobierno gestiona buena parte de los servicios sanitarios públicos?',
    optionA: 'Las comunidades autónomas',
    optionB: 'Solo la Unión Europea',
    optionC: 'Únicamente los ayuntamientos',
    optionD: 'El Tribunal Constitucional',
    correctOptionId: 'a',
    explanation: 'Las comunidades autónomas tienen competencias clave en la gestión sanitaria.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-266',
    task: 'Derechos y deberes fundamentales',
    topic: 'Igualdad de género',
    prompt: '¿Qué principio inspira las políticas para combatir la discriminación entre mujeres y hombres?',
    optionA: 'La igualdad efectiva',
    optionB: 'La desigualdad competitiva',
    optionC: 'La jerarquía social fija',
    optionD: 'La prioridad territorial',
    correctOptionId: 'a',
    explanation: 'La igualdad efectiva entre mujeres y hombres es un principio básico del ordenamiento.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-267',
    task: 'Derechos y deberes fundamentales',
    topic: 'Obligaciones tributarias',
    prompt: '¿Para qué sirven, en términos generales, los impuestos en un Estado social?',
    optionA: 'Para financiar servicios y gastos públicos',
    optionB: 'Para sustituir los salarios privados',
    optionC: 'Para elegir jueces',
    optionD: 'Para cerrar escuelas',
    correctOptionId: 'a',
    explanation: 'Los impuestos contribuyen a financiar servicios públicos y políticas comunes.',
    difficulty: 'fácil',
  ),
  _question(
    id: 'ccse-268',
    task: 'Derechos y deberes fundamentales',
    topic: 'Educación',
    prompt: '¿Qué objetivo social tiene especialmente el derecho a la educación?',
    optionA: 'Favorecer la formación y la igualdad de oportunidades',
    optionB: 'Reducir el acceso a la cultura',
    optionC: 'Eliminar los servicios públicos',
    optionD: 'Sustituir el derecho al trabajo',
    correctOptionId: 'a',
    explanation: 'La educación contribuye a la formación personal y a la igualdad de oportunidades.',
    difficulty: 'fácil',
  ),
  _question(
    id: 'ccse-269',
    task: 'Derechos y deberes fundamentales',
    topic: 'Reunión',
    prompt: '¿Qué derecho ampara reunirse pacíficamente con otras personas para expresar una opinión?',
    optionA: 'El derecho de reunión',
    optionB: 'El derecho notarial',
    optionC: 'El derecho hipotecario',
    optionD: 'El derecho aduanero',
    correctOptionId: 'a',
    explanation: 'La reunión pacífica está protegida como derecho fundamental.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-270',
    task: 'Derechos y deberes fundamentales',
    topic: 'Objeción de discriminación',
    prompt: 'Si una empresa rechaza a una persona por su origen sin motivo legal, ¿qué principio podría estar vulnerando?',
    optionA: 'El principio de no discriminación',
    optionB: 'El principio de territorialidad',
    optionC: 'El principio de publicidad institucional',
    optionD: 'El principio de sucesión',
    correctOptionId: 'a',
    explanation: 'La discriminación injustificada vulnera el principio de igualdad y no discriminación.',
    difficulty: 'alta',
  ),
  _question(
    id: 'ccse-271',
    task: 'Organización territorial de España. Geografía física y política',
    topic: 'Meseta Central',
    prompt: '¿Qué gran unidad de relieve ocupa una parte importante del interior peninsular?',
    optionA: 'La Meseta Central',
    optionB: 'Los Alpes',
    optionC: 'Los fiordos del norte',
    optionD: 'El valle del Po',
    correctOptionId: 'a',
    explanation: 'La Meseta Central es una de las principales unidades del relieve español.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-272',
    task: 'Organización territorial de España. Geografía física y política',
    topic: 'Municipio',
    prompt: '¿Qué término se usa para la entidad territorial básica de la organización local en España?',
    optionA: 'Municipio',
    optionB: 'Cantón',
    optionC: 'Distrito federal',
    optionD: 'Comarca marítima nacional',
    correctOptionId: 'a',
    explanation: 'El municipio es la entidad básica de la organización territorial local.',
    difficulty: 'fácil',
  ),
  _question(
    id: 'ccse-273',
    task: 'Organización territorial de España. Geografía física y política',
    topic: 'Cordilleras',
    prompt: '¿Qué cordillera separa en parte la Meseta de la zona norte peninsular?',
    optionA: 'La Cordillera Cantábrica',
    optionB: 'Los Apeninos',
    optionC: 'Los Urales',
    optionD: 'El Atlas exclusivamente',
    correctOptionId: 'a',
    explanation: 'La Cordillera Cantábrica es una de las cadenas montañosas principales del norte.',
    difficulty: 'alta',
  ),
  _question(
    id: 'ccse-274',
    task: 'Organización territorial de España. Geografía física y política',
    topic: 'Archipiélagos',
    prompt: '¿Qué comunidad autónoma está formada por islas en el mar Mediterráneo?',
    optionA: 'Illes Balears',
    optionB: 'La Rioja',
    optionC: 'Castilla-La Mancha',
    optionD: 'Extremadura',
    correctOptionId: 'a',
    explanation: 'Illes Balears es la comunidad autónoma insular situada en el Mediterráneo.',
    difficulty: 'fácil',
  ),
  _question(
    id: 'ccse-275',
    task: 'Organización territorial de España. Geografía física y política',
    topic: 'Costa',
    prompt: '¿Qué mar baña la costa oriental de la península ibérica?',
    optionA: 'El mar Mediterráneo',
    optionB: 'El mar Báltico',
    optionC: 'El mar Caspio',
    optionD: 'El mar Rojo',
    correctOptionId: 'a',
    explanation: 'La fachada oriental peninsular está bañada por el mar Mediterráneo.',
    difficulty: 'fácil',
  ),
  _question(
    id: 'ccse-276',
    task: 'Organización territorial de España. Geografía física y política',
    topic: 'Estatuto de Autonomía',
    prompt: '¿Qué norma institucional básica organiza cada comunidad autónoma?',
    optionA: 'El Estatuto de Autonomía',
    optionB: 'El código postal',
    optionC: 'El presupuesto municipal',
    optionD: 'La matrícula provincial',
    correctOptionId: 'a',
    explanation: 'Cada comunidad autónoma se organiza conforme a su Estatuto de Autonomía.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-277',
    task: 'Organización territorial de España. Geografía física y política',
    topic: 'Mapa político',
    prompt: '¿Cuál de estas comunidades autónomas se encuentra en el norte de España?',
    optionA: 'Asturias',
    optionB: 'Canarias',
    optionC: 'Murcia',
    optionD: 'Andalucía occidental entera',
    correctOptionId: 'a',
    explanation: 'Asturias se sitúa en la franja norte peninsular.',
    difficulty: 'fácil',
  ),
  _question(
    id: 'ccse-278',
    task: 'Organización territorial de España. Geografía física y política',
    topic: 'Cabildos y consejos',
    prompt: '¿Qué institución administra cada isla en Canarias?',
    optionA: 'El cabildo insular',
    optionB: 'La diputación europea',
    optionC: 'El consejo de ministros',
    optionD: 'La audiencia nacional',
    correctOptionId: 'a',
    explanation: 'En Canarias, cada isla cuenta con un cabildo insular.',
    difficulty: 'alta',
  ),
  _question(
    id: 'ccse-279',
    task: 'Organización territorial de España. Geografía física y política',
    topic: 'Lenguas cooficiales',
    prompt: '¿En qué tipo de territorio se reconocen, además del castellano, otras lenguas cooficiales?',
    optionA: 'En algunas comunidades autónomas',
    optionB: 'En todos los municipios por igual',
    optionC: 'Solo en el extranjero',
    optionD: 'Únicamente en las provincias costeras',
    correctOptionId: 'a',
    explanation: 'Algunas comunidades autónomas reconocen otras lenguas cooficiales.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-280',
    task: 'Cultura e historia de España',
    topic: 'Siglo de Oro',
    prompt: '¿Cómo se conoce el periodo de gran esplendor artístico y literario español entre los siglos XVI y XVII?',
    optionA: 'El Siglo de Oro',
    optionB: 'La Revolución Industrial',
    optionC: 'La Restauración ferroviaria',
    optionD: 'La Edad de Plata científica exclusivamente',
    correctOptionId: 'a',
    explanation: 'Ese periodo es conocido como el Siglo de Oro español.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-281',
    task: 'Cultura e historia de España',
    topic: 'Convivencia cultural',
    prompt: '¿Qué ciudad andaluza es conocida por monumentos como la Mezquita-Catedral?',
    optionA: 'Córdoba',
    optionB: 'Burgos',
    optionC: 'León',
    optionD: 'Santander',
    correctOptionId: 'a',
    explanation: 'La Mezquita-Catedral es uno de los símbolos monumentales de Córdoba.',
    difficulty: 'fácil',
  ),
  _question(
    id: 'ccse-282',
    task: 'Cultura e historia de España',
    topic: 'Arquitectura',
    prompt: '¿Qué arquitecto está especialmente vinculado a edificios modernistas de Barcelona?',
    optionA: 'Antoni Gaudí',
    optionB: 'Le Corbusier',
    optionC: 'Norman Foster',
    optionD: 'Mies van der Rohe exclusivamente en España',
    correctOptionId: 'a',
    explanation: 'Gaudí es la figura más representativa del modernismo barcelonés.',
    difficulty: 'fácil',
  ),
  _question(
    id: 'ccse-283',
    task: 'Cultura e historia de España',
    topic: 'Historia medieval',
    prompt: '¿Qué periodo histórico estuvo marcado por la coexistencia de culturas cristiana, musulmana y judía en distintos territorios de la península?',
    optionA: 'Parte de la Edad Media',
    optionB: 'La Edad de Hielo',
    optionC: 'La transición energética',
    optionD: 'La globalización financiera',
    correctOptionId: 'a',
    explanation: 'Durante la Edad Media se dieron etapas de coexistencia cultural en la península.',
    difficulty: 'alta',
  ),
  _question(
    id: 'ccse-284',
    task: 'Cultura e historia de España',
    topic: 'Patrimonio mundial',
    prompt: '¿Qué monumento granadino es un referente del patrimonio histórico español?',
    optionA: 'La Alhambra',
    optionB: 'La Giralda de Lisboa',
    optionC: 'El Coliseo',
    optionD: 'La torre Eiffel',
    correctOptionId: 'a',
    explanation: 'La Alhambra es uno de los conjuntos monumentales más reconocidos de España.',
    difficulty: 'fácil',
  ),
  _question(
    id: 'ccse-285',
    task: 'Cultura e historia de España',
    topic: 'Universidades históricas',
    prompt: '¿Qué ciudad es conocida por una de las universidades más antiguas de Europa?',
    optionA: 'Salamanca',
    optionB: 'Benidorm',
    optionC: 'Torrevieja',
    optionD: 'Marbella',
    correctOptionId: 'a',
    explanation: 'La Universidad de Salamanca es una de las instituciones académicas históricas de Europa.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-286',
    task: 'Cultura e historia de España',
    topic: 'Pintura clásica',
    prompt: '¿Qué pintor español es autor de Las Meninas?',
    optionA: 'Diego Velázquez',
    optionB: 'Joaquín Sorolla',
    optionC: 'Joan Miró',
    optionD: 'Antoni Tàpies',
    correctOptionId: 'a',
    explanation: 'Las Meninas es una de las obras más conocidas de Velázquez.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-287',
    task: 'Cultura e historia de España',
    topic: 'Constitución',
    prompt: '¿Qué día festivo nacional conmemora la Constitución española?',
    optionA: '6 de diciembre',
    optionB: '1 de enero',
    optionC: '15 de agosto',
    optionD: '31 de diciembre',
    correctOptionId: 'a',
    explanation: 'El Día de la Constitución se celebra el 6 de diciembre.',
    difficulty: 'fácil',
  ),
  _question(
    id: 'ccse-288',
    task: 'Cultura e historia de España',
    topic: 'Deporte',
    prompt: '¿Qué competición ciclista por etapas de prestigio internacional se celebra en España?',
    optionA: 'La Vuelta a España',
    optionB: 'El Tour de Portugal',
    optionC: 'El Giro Ibérico',
    optionD: 'La Ruta Atlántica Universal',
    correctOptionId: 'a',
    explanation: 'La Vuelta a España es una de las grandes carreras ciclistas por etapas.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-289',
    task: 'Cultura e historia de España',
    topic: 'Tradición festiva',
    prompt: '¿En qué ciudad se celebran los sanfermines?',
    optionA: 'Pamplona',
    optionB: 'Toledo',
    optionC: 'Alicante',
    optionD: 'Cáceres',
    correctOptionId: 'a',
    explanation: 'Los sanfermines son una celebración emblemática de Pamplona.',
    difficulty: 'fácil',
  ),
  _question(
    id: 'ccse-290',
    task: 'Sociedad española',
    topic: 'Centros de salud',
    prompt: '¿A qué lugar suele acudir primero una persona para atención sanitaria no urgente dentro del sistema público?',
    optionA: 'Al centro de salud',
    optionB: 'A la jefatura de tráfico',
    optionC: 'Al consulado',
    optionD: 'A la oficina de empleo sin cita',
    correctOptionId: 'a',
    explanation: 'La atención primaria se presta habitualmente en centros de salud.',
    difficulty: 'fácil',
  ),
  _question(
    id: 'ccse-291',
    task: 'Sociedad española',
    topic: 'Biblioteca',
    prompt: '¿Qué documento suele necesitarse para llevar libros prestados de una biblioteca pública?',
    optionA: 'El carné de biblioteca',
    optionB: 'La tarjeta censal',
    optionC: 'La licencia de obras',
    optionD: 'El pasaporte diplomático',
    correctOptionId: 'a',
    explanation: 'Las bibliotecas suelen expedir un carné para el préstamo de libros.',
    difficulty: 'fácil',
  ),
  _question(
    id: 'ccse-292',
    task: 'Sociedad española',
    topic: 'Empleo',
    prompt: '¿Qué servicio público ayuda a buscar empleo y gestionar prestaciones relacionadas?',
    optionA: 'El servicio público de empleo',
    optionB: 'La oficina meteorológica',
    optionC: 'La lotería nacional',
    optionD: 'La policía portuaria',
    correctOptionId: 'a',
    explanation: 'Los servicios públicos de empleo orientan y gestionan trámites laborales.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-293',
    task: 'Sociedad española',
    topic: 'Escuela',
    prompt: '¿Qué etapa educativa cursan normalmente los niños antes de la educación secundaria obligatoria?',
    optionA: 'La educación primaria',
    optionB: 'La universidad',
    optionC: 'El doctorado',
    optionD: 'La formación judicial',
    correctOptionId: 'a',
    explanation: 'La educación primaria precede a la educación secundaria obligatoria.',
    difficulty: 'fácil',
  ),
  _question(
    id: 'ccse-294',
    task: 'Sociedad española',
    topic: 'Medios de pago',
    prompt: '¿Qué documento o medio permite normalmente identificar una cuenta bancaria para recibir una nómina?',
    optionA: 'El número de cuenta o IBAN',
    optionB: 'La matrícula del coche',
    optionC: 'El código postal',
    optionD: 'El número de biblioteca',
    correctOptionId: 'a',
    explanation: 'El IBAN identifica una cuenta bancaria y se usa en muchas gestiones económicas.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-295',
    task: 'Sociedad española',
    topic: 'Vecindad',
    prompt: '¿Qué actitud es adecuada cuando se comparte un espacio común en una comunidad de propietarios?',
    optionA: 'Mantener limpieza y respetar las normas del edificio',
    optionB: 'Usarlo sin atender a horarios ni avisos',
    optionC: 'Impedir el paso a otros vecinos',
    optionD: 'Guardar objetos peligrosos en zonas comunes',
    correctOptionId: 'a',
    explanation: 'El respeto a las normas comunes favorece la convivencia vecinal.',
    difficulty: 'fácil',
  ),
  _question(
    id: 'ccse-296',
    task: 'Sociedad española',
    topic: 'Compra',
    prompt: '¿Qué documento conviene guardar tras una compra por si fuera necesario reclamar?',
    optionA: 'El ticket o factura',
    optionB: 'El padrón',
    optionC: 'El certificado de nacimiento',
    optionD: 'El volante de empadronamiento siempre',
    correctOptionId: 'a',
    explanation: 'El ticket o factura sirve como justificante para cambios o reclamaciones.',
    difficulty: 'fácil',
  ),
  _question(
    id: 'ccse-297',
    task: 'Sociedad española',
    topic: 'Integración social',
    prompt: '¿Qué favorece la integración en la vida cotidiana de una persona recién llegada a España?',
    optionA: 'Conocer la lengua y los servicios básicos',
    optionB: 'Evitar cualquier relación con el entorno',
    optionC: 'No realizar ningún trámite administrativo',
    optionD: 'Ignorar las normas comunes',
    correctOptionId: 'a',
    explanation: 'La lengua y el conocimiento de los servicios ayudan a la integración social.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-298',
    task: 'Sociedad española',
    topic: 'Atención al ciudadano',
    prompt: '¿Qué servicio municipal suele informar sobre actividades del barrio o trámites locales?',
    optionA: 'La oficina de atención ciudadana',
    optionB: 'La embajada de otro país',
    optionC: 'El tribunal de oposiciones',
    optionD: 'La casa de apuestas',
    correctOptionId: 'a',
    explanation: 'Las oficinas de atención ciudadana orientan sobre trámites y servicios municipales.',
    difficulty: 'media',
  ),
  _question(
    id: 'ccse-299',
    task: 'Sociedad española',
    topic: 'Reciclaje doméstico',
    prompt: '¿Por qué es útil separar residuos en casa?',
    optionA: 'Porque facilita el reciclaje y el cuidado del medio ambiente',
    optionB: 'Porque elimina la necesidad de servicios públicos',
    optionC: 'Porque sustituye la educación ambiental',
    optionD: 'Porque evita pagar cualquier tasa municipal',
    correctOptionId: 'a',
    explanation: 'Separar residuos facilita su tratamiento y mejora la sostenibilidad ambiental.',
    difficulty: 'fácil',
  ),
  _question(
    id: 'ccse-300',
    task: 'Sociedad española',
    topic: 'Convivencia',
    prompt: '¿Qué valor es clave para convivir en una sociedad plural como la española?',
    optionA: 'El respeto a las diferencias',
    optionB: 'La imposición de una única costumbre',
    optionC: 'El rechazo a toda diversidad',
    optionD: 'La exclusión social',
    correctOptionId: 'a',
    explanation: 'El respeto a las diferencias es esencial en una sociedad diversa y democrática.',
    difficulty: 'fácil',
  ),
];

QuestionModel _question({
  required String id,
  required String task,
  required String topic,
  required String prompt,
  required String optionA,
  required String optionB,
  required String optionC,
  required String optionD,
  required String correctOptionId,
  required String explanation,
  required String difficulty,
}) {
  return QuestionModel(
    id: id,
    exam: 'CCSE',
    task: task,
    topic: topic,
    prompt: prompt,
    options: [
      QuestionOption(id: 'a', text: optionA, isCorrect: correctOptionId == 'a'),
      QuestionOption(id: 'b', text: optionB, isCorrect: correctOptionId == 'b'),
      QuestionOption(id: 'c', text: optionC, isCorrect: correctOptionId == 'c'),
      QuestionOption(id: 'd', text: optionD, isCorrect: correctOptionId == 'd'),
    ],
    correctOptionId: correctOptionId,
    explanation: explanation,
    difficulty: difficulty,
    sourceReference: 'Instituto Cervantes + elaboración propia',
    contentVersion: 'v3',
  );
}
