import '../models/question_model.dart';

final List<QuestionModel> ccseCoreQuestions = [
  QuestionModel(
    id: 'ccse-01',
    exam: 'CCSE',
    task: 'Gobierno, legislación y participación ciudadana',
    topic: 'Cortes Generales',
    prompt: '¿Qué función principal tienen las Cortes Generales en el sistema político español?',
    options: [
      const QuestionOption(id: 'a', text: 'Nombrar a los jueces', isCorrect: false),
      const QuestionOption(id: 'b', text: 'Aprobar leyes y controlar al Gobierno', isCorrect: true),
      const QuestionOption(id: 'c', text: 'Gestionar los hospitales', isCorrect: false),
      const QuestionOption(id: 'd', text: 'Organizar la educación superior', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'Las Cortes Generales elaboran leyes y ejercen control democrático sobre el Gobierno.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-02',
    exam: 'CCSE',
    task: 'Derechos y deberes fundamentales',
    topic: 'Deberes constitucionales',
    prompt: '¿Cuál de estas opciones representa un deber básico recogido en la Constitución?',
    options: [
      const QuestionOption(id: 'a', text: 'Votar en todas las elecciones', isCorrect: false),
      const QuestionOption(id: 'b', text: 'Respetar los derechos de los demás', isCorrect: true),
      const QuestionOption(id: 'c', text: 'Elegir a los jueces', isCorrect: false),
      const QuestionOption(id: 'd', text: 'Designar al presidente del Gobierno', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'La convivencia democrática exige respetar los derechos fundamentales de otras personas.',
    difficulty: 'fácil',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-03',
    exam: 'CCSE',
    task: 'Organización territorial de España. Geografía física y política',
    topic: 'Municipios',
    prompt: '¿Qué institución gestiona de forma más cercana los asuntos locales en un municipio?',
    options: [
      const QuestionOption(id: 'a', text: 'El Gobierno central', isCorrect: false),
      const QuestionOption(id: 'b', text: 'El Parlamento europeo', isCorrect: false),
      const QuestionOption(id: 'c', text: 'El ayuntamiento', isCorrect: true),
      const QuestionOption(id: 'd', text: 'El Tribunal Constitucional', isCorrect: false),
    ],
    correctOptionId: 'c',
    explanation: 'El ayuntamiento es la institución local con competencias cercanas a la vida diaria.',
    difficulty: 'fácil',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-04',
    exam: 'CCSE',
    task: 'Cultura e historia de España',
    topic: 'Historia contemporánea',
    prompt: '¿Qué acontecimiento suele relacionarse con el inicio de la España contemporánea?',
    options: [
      const QuestionOption(id: 'a', text: 'La caída del Imperio romano', isCorrect: false),
      const QuestionOption(id: 'b', text: 'La Guerra de la Independencia', isCorrect: true),
      const QuestionOption(id: 'c', text: 'La conquista de Granada', isCorrect: false),
      const QuestionOption(id: 'd', text: 'La expansión del Renacimiento', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'La Guerra de la Independencia marcó un hito en la historia contemporánea española.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-05',
    exam: 'CCSE',
    task: 'Sociedad española',
    topic: 'Diversidad social',
    prompt: '¿Cuál es una característica relevante de la sociedad española actual?',
    options: [
      const QuestionOption(id: 'a', text: 'Carece de diversidad cultural', isCorrect: false),
      const QuestionOption(id: 'b', text: 'Está formada por una única lengua oficial', isCorrect: false),
      const QuestionOption(id: 'c', text: 'Presenta una gran pluralidad cultural y social', isCorrect: true),
      const QuestionOption(id: 'd', text: 'No participa en asociaciones vecinales', isCorrect: false),
    ],
    correctOptionId: 'c',
    explanation: 'La sociedad española es plural y diversa, con múltiples influencias culturales.',
    difficulty: 'fácil',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-06',
    exam: 'CCSE',
    task: 'Gobierno, legislación y participación ciudadana',
    topic: 'Democracia',
    prompt: '¿Qué significa que España sea una monarquía parlamentaria?',
    options: [
      const QuestionOption(id: 'a', text: 'El rey gobierna sin límites', isCorrect: false),
      const QuestionOption(id: 'b', text: 'El rey es jefe del Estado y el Gobierno depende del poder legislativo', isCorrect: true),
      const QuestionOption(id: 'c', text: 'El rey elige a todos los diputados', isCorrect: false),
      const QuestionOption(id: 'd', text: 'No existe separación de poderes', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'En una monarquía parlamentaria, el rey es jefe del Estado, pero el poder político se ejerce mediante instituciones democráticas.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-07',
    exam: 'CCSE',
    task: 'Derechos y deberes fundamentales',
    topic: 'Libertad de expresión',
    prompt: '¿Qué derecho protege la libertad de opinión en España?',
    options: [
      const QuestionOption(id: 'a', text: 'El derecho a la propiedad privada', isCorrect: false),
      const QuestionOption(id: 'b', text: 'El derecho a la libertad de expresión', isCorrect: true),
      const QuestionOption(id: 'c', text: 'El derecho a la educación obligatoria', isCorrect: false),
      const QuestionOption(id: 'd', text: 'El derecho a la sanidad universal', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'La Constitución reconoce la libertad de expresión como un derecho fundamental.',
    difficulty: 'fácil',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-08',
    exam: 'CCSE',
    task: 'Organización territorial de España. Geografía física y política',
    topic: 'Comunidades autónomas',
    prompt: '¿Cuál es la principal unidad territorial de descentralización en España?',
    options: [
      const QuestionOption(id: 'a', text: 'Las provincias', isCorrect: false),
      const QuestionOption(id: 'b', text: 'Las comunidades autónomas', isCorrect: true),
      const QuestionOption(id: 'c', text: 'Los municipios', isCorrect: false),
      const QuestionOption(id: 'd', text: 'Los barrios', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'Las comunidades autónomas son el principal marco de descentralización política y administrativa.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-09',
    exam: 'CCSE',
    task: 'Cultura e historia de España',
    topic: 'Patrimonio',
    prompt: '¿Qué elemento suele considerarse una muestra destacada del patrimonio cultural español?',
    options: [
      const QuestionOption(id: 'a', text: 'El sistema de metro', isCorrect: false),
      const QuestionOption(id: 'b', text: 'La Alhambra', isCorrect: true),
      const QuestionOption(id: 'c', text: 'La banca central', isCorrect: false),
      const QuestionOption(id: 'd', text: 'La red ferroviaria', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'La Alhambra es un ejemplo emblemático del patrimonio histórico y artístico español.',
    difficulty: 'fácil',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-10',
    exam: 'CCSE',
    task: 'Sociedad española',
    topic: 'Población',
    prompt: '¿Qué fenómeno ha influido en la composición actual de la población española?',
    options: [
      const QuestionOption(id: 'a', text: 'La desaparición de las ciudades', isCorrect: false),
      const QuestionOption(id: 'b', text: 'La inmigración', isCorrect: true),
      const QuestionOption(id: 'c', text: 'La ausencia de movilidad', isCorrect: false),
      const QuestionOption(id: 'd', text: 'La disminución del trabajo', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'La inmigración ha sido un factor clave en la transformación demográfica reciente.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-11',
    exam: 'CCSE',
    task: 'Gobierno, legislación y participación ciudadana',
    topic: 'Elecciones',
    prompt: '¿Qué ocurre cuando se celebran elecciones en España?',
    options: [
      const QuestionOption(id: 'a', text: 'Se elige a todos los jueces', isCorrect: false),
      const QuestionOption(id: 'b', text: 'Se renueva el Parlamento', isCorrect: true),
      const QuestionOption(id: 'c', text: 'Se cambia la Constitución', isCorrect: false),
      const QuestionOption(id: 'd', text: 'Se disuelven los ayuntamientos', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'Las elecciones permiten renovar las instituciones representativas del país.',
    difficulty: 'fácil',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-12',
    exam: 'CCSE',
    task: 'Derechos y deberes fundamentales',
    topic: 'Igualdad',
    prompt: '¿Qué principio protege la igualdad ante la ley?',
    options: [
      const QuestionOption(id: 'a', text: 'El principio de jerarquía', isCorrect: false),
      const QuestionOption(id: 'b', text: 'El principio de igualdad', isCorrect: true),
      const QuestionOption(id: 'c', text: 'El principio de autoridad', isCorrect: false),
      const QuestionOption(id: 'd', text: 'El principio de tradición', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'La igualdad ante la ley es un principio central de la Constitución.',
    difficulty: 'fácil',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-13',
    exam: 'CCSE',
    task: 'Organización territorial de España. Geografía física y política',
    topic: 'Geografía',
    prompt: '¿Qué característica define en parte la geografía física de España?',
    options: [
      const QuestionOption(id: 'a', text: 'Su ausencia de costas', isCorrect: false),
      const QuestionOption(id: 'b', text: 'Su variedad de relieves y costas', isCorrect: true),
      const QuestionOption(id: 'c', text: 'Su ubicación exclusivamente en el norte', isCorrect: false),
      const QuestionOption(id: 'd', text: 'Su clima uniforme', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'España presenta una gran variedad de relieves y una extensa costa.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-14',
    exam: 'CCSE',
    task: 'Cultura e historia de España',
    topic: 'Lengua',
    prompt: '¿Qué lengua comparte el Estado español además del castellano?',
    options: [
      const QuestionOption(id: 'a', text: 'El francés', isCorrect: false),
      const QuestionOption(id: 'b', text: 'El italiano', isCorrect: false),
      const QuestionOption(id: 'c', text: 'Las lenguas cooficiales de algunas comunidades', isCorrect: true),
      const QuestionOption(id: 'd', text: 'El alemán', isCorrect: false),
    ],
    correctOptionId: 'c',
    explanation: 'En algunas comunidades autónomas coexisten lenguas cooficiales junto al castellano.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-15',
    exam: 'CCSE',
    task: 'Sociedad española',
    topic: 'Educación',
    prompt: '¿Qué papel tiene la educación en la sociedad española?',
    options: [
      const QuestionOption(id: 'a', text: 'No influye en la integración', isCorrect: false),
      const QuestionOption(id: 'b', text: 'Es un elemento clave para la integración y la movilidad', isCorrect: true),
      const QuestionOption(id: 'c', text: 'Solo sirve para la universidad', isCorrect: false),
      const QuestionOption(id: 'd', text: 'No es obligatoria', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'La educación contribuye a la integración social y a la formación personal.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-16',
    exam: 'CCSE',
    task: 'Gobierno, legislación y participación ciudadana',
    topic: 'Participación',
    prompt: '¿Qué forma de participación ciudadana es habitual en la vida democrática?',
    options: [
      const QuestionOption(id: 'a', text: 'El boicot a las elecciones', isCorrect: false),
      const QuestionOption(id: 'b', text: 'La participación en asociaciones y movimientos sociales', isCorrect: true),
      const QuestionOption(id: 'c', text: 'La abstención activa', isCorrect: false),
      const QuestionOption(id: 'd', text: 'La violencia política', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'La participación en asociaciones y movimientos sociales es una vía normal de implicación democrática.',
    difficulty: 'fácil',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-17',
    exam: 'CCSE',
    task: 'Derechos y deberes fundamentales',
    topic: 'Derechos sociales',
    prompt: '¿Qué derecho facilita el acceso a la protección sanitaria?',
    options: [
      const QuestionOption(id: 'a', text: 'El derecho a la vivienda', isCorrect: false),
      const QuestionOption(id: 'b', text: 'El derecho a la salud', isCorrect: true),
      const QuestionOption(id: 'c', text: 'El derecho a la jubilación automática', isCorrect: false),
      const QuestionOption(id: 'd', text: 'El derecho al trabajo exclusivo', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'El derecho a la salud es un pilar de la protección social en España.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-18',
    exam: 'CCSE',
    task: 'Organización territorial de España. Geografía física y política',
    topic: 'Capitales',
    prompt: '¿Cuál es la capital de España?',
    options: [
      const QuestionOption(id: 'a', text: 'Barcelona', isCorrect: false),
      const QuestionOption(id: 'b', text: 'Sevilla', isCorrect: false),
      const QuestionOption(id: 'c', text: 'Madrid', isCorrect: true),
      const QuestionOption(id: 'd', text: 'Valencia', isCorrect: false),
    ],
    correctOptionId: 'c',
    explanation: 'Madrid es la capital del Estado español.',
    difficulty: 'fácil',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-19',
    exam: 'CCSE',
    task: 'Cultura e historia de España',
    topic: 'Arte',
    prompt: '¿Qué movimiento artístico está muy ligado a la figura de Velázquez?',
    options: [
      const QuestionOption(id: 'a', text: 'El barroco', isCorrect: true),
      const QuestionOption(id: 'b', text: 'El romanticismo', isCorrect: false),
      const QuestionOption(id: 'c', text: 'El cubismo', isCorrect: false),
      const QuestionOption(id: 'd', text: 'El impresionismo', isCorrect: false),
    ],
    correctOptionId: 'a',
    explanation: 'Velázquez es uno de los grandes representantes del barroco español.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-20',
    exam: 'CCSE',
    task: 'Sociedad española',
    topic: 'Tradiciones',
    prompt: '¿Qué papel tienen las fiestas y tradiciones en la vida social española?',
    options: [
      const QuestionOption(id: 'a', text: 'No representan identidad', isCorrect: false),
      const QuestionOption(id: 'b', text: 'Refuerzan la identidad y la convivencia', isCorrect: true),
      const QuestionOption(id: 'c', text: 'Solo tienen valor turístico', isCorrect: false),
      const QuestionOption(id: 'd', text: 'Se celebran solo en verano', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'Las tradiciones y fiestas contribuyen a la identidad colectiva y a los vínculos sociales.',
    difficulty: 'fácil',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-21',
    exam: 'CCSE',
    task: 'Gobierno, legislación y participación ciudadana',
    topic: 'Instituciones',
    prompt: '¿Qué papel cumple el Gobierno en el sistema político español?',
    options: [
      const QuestionOption(id: 'a', text: 'Dirigir la administración y ejecutar las políticas públicas', isCorrect: true),
      const QuestionOption(id: 'b', text: 'Nombrar al rey', isCorrect: false),
      const QuestionOption(id: 'c', text: 'Elegir los jueces', isCorrect: false),
      const QuestionOption(id: 'd', text: 'Modificar la Constitución', isCorrect: false),
    ],
    correctOptionId: 'a',
    explanation: 'El Gobierno dirige la administración y pone en marcha las decisiones políticas.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-22',
    exam: 'CCSE',
    task: 'Derechos y deberes fundamentales',
    topic: 'Libertad religiosa',
    prompt: '¿Qué derecho protege la libertad de conciencia?',
    options: [
      const QuestionOption(id: 'a', text: 'La libertad religiosa', isCorrect: true),
      const QuestionOption(id: 'b', text: 'La libertad de movilidad', isCorrect: false),
      const QuestionOption(id: 'c', text: 'La libertad de empresa', isCorrect: false),
      const QuestionOption(id: 'd', text: 'La libertad de consumo', isCorrect: false),
    ],
    correctOptionId: 'a',
    explanation: 'La libertad religiosa es un derecho fundamental que protege la conciencia personal.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-23',
    exam: 'CCSE',
    task: 'Organización territorial de España. Geografía física y política',
    topic: 'Ríos',
    prompt: '¿Qué papel tienen los ríos en la geografía española?',
    options: [
      const QuestionOption(id: 'a', text: 'No tienen importancia', isCorrect: false),
      const QuestionOption(id: 'b', text: 'Influyen en la distribución humana y económica', isCorrect: true),
      const QuestionOption(id: 'c', text: 'Solo sirven para el turismo', isCorrect: false),
      const QuestionOption(id: 'd', text: 'Solo existen en el norte', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'Los ríos han condicionado históricamente el poblamiento y la economía.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-24',
    exam: 'CCSE',
    task: 'Cultura e historia de España',
    topic: 'Literatura',
    prompt: '¿Qué figura destaca en la literatura española clásica?',
    options: [
      const QuestionOption(id: 'a', text: 'Miguel de Cervantes', isCorrect: true),
      const QuestionOption(id: 'b', text: 'Pablo Picasso', isCorrect: false),
      const QuestionOption(id: 'c', text: 'Federico García Lorca', isCorrect: false),
      const QuestionOption(id: 'd', text: 'Antonio Banderas', isCorrect: false),
    ],
    correctOptionId: 'a',
    explanation: 'Cervantes es una de las figuras esenciales de la literatura española.',
    difficulty: 'fácil',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-25',
    exam: 'CCSE',
    task: 'Sociedad española',
    topic: 'Inmigración',
    prompt: '¿Cómo ha influido la inmigración en la sociedad española?',
    options: [
      const QuestionOption(id: 'a', text: 'Ha reducido la riqueza cultural', isCorrect: false),
      const QuestionOption(id: 'b', text: 'Ha enriquecido la cultura y el tejido social', isCorrect: true),
      const QuestionOption(id: 'c', text: 'Ha eliminado la diversidad', isCorrect: false),
      const QuestionOption(id: 'd', text: 'Ha reducido la población', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'La inmigración ha contribuido a la diversidad cultural y al desarrollo social.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-26',
    exam: 'CCSE',
    task: 'Gobierno, legislación y participación ciudadana',
    topic: 'Parlamento',
    prompt: '¿Cuál es una función esencial del Parlamento en un sistema democrático?',
    options: [
      const QuestionOption(id: 'a', text: 'Ejercer la función judicial', isCorrect: false),
      const QuestionOption(id: 'b', text: 'Representar a la ciudadanía y aprobar leyes', isCorrect: true),
      const QuestionOption(id: 'c', text: 'Dirigir los servicios de emergencia', isCorrect: false),
      const QuestionOption(id: 'd', text: 'Gestionar exclusivamente la sanidad', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'El Parlamento representa a la ciudadanía y tiene una función legislativa central.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-27',
    exam: 'CCSE',
    task: 'Derechos y deberes fundamentales',
    topic: 'Participación',
    prompt: '¿Qué obligación suele acompañar a la participación política en una democracia?',
    options: [
      const QuestionOption(id: 'a', text: 'Respetar las normas y los derechos de los demás', isCorrect: true),
      const QuestionOption(id: 'b', text: 'No respetar ninguna ley', isCorrect: false),
      const QuestionOption(id: 'c', text: 'Evitar toda asociación', isCorrect: false),
      const QuestionOption(id: 'd', text: 'Impedir la libertad de expresión', isCorrect: false),
    ],
    correctOptionId: 'a',
    explanation: 'La participación democrática exige respetar las normas y los derechos de los demás.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-28',
    exam: 'CCSE',
    task: 'Organización territorial de España. Geografía física y política',
    topic: 'Provincias',
    prompt: '¿Qué papel tienen las provincias dentro del mapa territorial español?',
    options: [
      const QuestionOption(id: 'a', text: 'Solo sirven para fines turísticos', isCorrect: false),
      const QuestionOption(id: 'b', text: 'Constituyen una división administrativa importante', isCorrect: true),
      const QuestionOption(id: 'c', text: 'No existen en la organización territorial', isCorrect: false),
      const QuestionOption(id: 'd', text: 'Son únicamente municipios grandes', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'Las provincias forman parte de la organización territorial y de la administración del Estado.',
    difficulty: 'fácil',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-29',
    exam: 'CCSE',
    task: 'Cultura e historia de España',
    topic: 'Monarquía',
    prompt: '¿Qué papel histórico ha tenido la monarquía en la historia de España?',
    options: [
      const QuestionOption(id: 'a', text: 'Ha sido irrelevante en la historia reciente', isCorrect: false),
      const QuestionOption(id: 'b', text: 'Ha formado parte de la tradición institucional del país', isCorrect: true),
      const QuestionOption(id: 'c', text: 'Solo ha existido en la Edad Media', isCorrect: false),
      const QuestionOption(id: 'd', text: 'No tiene relación con la Constitución', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'La monarquía ha sido una institución histórica relevante en España.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-30',
    exam: 'CCSE',
    task: 'Sociedad española',
    topic: 'Economía',
    prompt: '¿Qué relación existe entre la economía y la vida cotidiana en España?',
    options: [
      const QuestionOption(id: 'a', text: 'No tiene impacto alguno', isCorrect: false),
      const QuestionOption(id: 'b', text: 'Influye en empleo, servicios y oportunidades', isCorrect: true),
      const QuestionOption(id: 'c', text: 'Solo afecta a la agricultura', isCorrect: false),
      const QuestionOption(id: 'd', text: 'Solo afecta a los grandes empresarios', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'La economía influye en el empleo, los servicios y la calidad de vida.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-31',
    exam: 'CCSE',
    task: 'Gobierno, legislación y participación ciudadana',
    topic: 'Gobierno',
    prompt: '¿Qué función principal desarrolla el Gobierno en el sistema político español?',
    options: [
      const QuestionOption(id: 'a', text: 'Proponer leyes y ejecutar políticas públicas', isCorrect: true),
      const QuestionOption(id: 'b', text: 'Elegir a los jueces del Supremo', isCorrect: false),
      const QuestionOption(id: 'c', text: 'Designar al rey', isCorrect: false),
      const QuestionOption(id: 'd', text: 'Fundar partidos políticos', isCorrect: false),
    ],
    correctOptionId: 'a',
    explanation: 'El Gobierno propone iniciativas y ejecuta decisiones políticas y administrativas.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-32',
    exam: 'CCSE',
    task: 'Derechos y deberes fundamentales',
    topic: 'Educación',
    prompt: '¿Por qué se considera importante el derecho a la educación?',
    options: [
      const QuestionOption(id: 'a', text: 'Porque garantiza la igualdad de oportunidades', isCorrect: true),
      const QuestionOption(id: 'b', text: 'Porque elimina la necesidad de votar', isCorrect: false),
      const QuestionOption(id: 'c', text: 'Porque sustituye a los tribunales', isCorrect: false),
      const QuestionOption(id: 'd', text: 'Porque solo afecta a los adultos', isCorrect: false),
    ],
    correctOptionId: 'a',
    explanation: 'La educación favorece la igualdad de oportunidades y el desarrollo personal.',
    difficulty: 'fácil',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-33',
    exam: 'CCSE',
    task: 'Organización territorial de España. Geografía física y política',
    topic: 'Coordenadas',
    prompt: '¿Qué ventaja tiene la ubicación geográfica de España?',
    options: [
      const QuestionOption(id: 'a', text: 'No tiene relación con el comercio', isCorrect: false),
      const QuestionOption(id: 'b', text: 'Favorece las relaciones con otros continentes', isCorrect: true),
      const QuestionOption(id: 'c', text: 'La aísla de todos los vecinos', isCorrect: false),
      const QuestionOption(id: 'd', text: 'Impide el desarrollo turístico', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'La posición de España en Europa y el Mediterráneo ha favorecido históricamente las relaciones externas.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-34',
    exam: 'CCSE',
    task: 'Cultura e historia de España',
    topic: 'Arte',
    prompt: '¿Qué importancia tiene el patrimonio artístico en la identidad española?',
    options: [
      const QuestionOption(id: 'a', text: 'No influye en la identidad colectiva', isCorrect: false),
      const QuestionOption(id: 'b', text: 'Contribuye a reforzar la memoria cultural', isCorrect: true),
      const QuestionOption(id: 'c', text: 'Solo interesa a los historiadores', isCorrect: false),
      const QuestionOption(id: 'd', text: 'Se limita a los museos de Madrid', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'El patrimonio artístico ayuda a conservar la memoria cultural y la identidad del país.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
  QuestionModel(
    id: 'ccse-35',
    exam: 'CCSE',
    task: 'Sociedad española',
    topic: 'Demografía',
    prompt: '¿Qué efecto tiene el envejecimiento de la población en la sociedad española?',
    options: [
      const QuestionOption(id: 'a', text: 'No tiene ninguna consecuencia', isCorrect: false),
      const QuestionOption(id: 'b', text: 'Implica retos sociales y económicos', isCorrect: true),
      const QuestionOption(id: 'c', text: 'Reduce la importancia del trabajo', isCorrect: false),
      const QuestionOption(id: 'd', text: 'Elimina la necesidad de servicios públicos', isCorrect: false),
    ],
    correctOptionId: 'b',
    explanation: 'El envejecimiento poblacional genera retos relacionados con la economía y los servicios.',
    difficulty: 'media',
    sourceReference: 'Instituto Cervantes',
    contentVersion: 'v1',
  ),
];